<!DOCTYPE html>
<html lang="es">

<!-- Latest compiled and minified CSS & JS -->
<!--<link rel="stylesheet" media="screen" href="<?php echo $_layoutParams?>/css/bootstrap.min.css">
<script src="<?php echo $_layoutParams?>/jquery.js"></script>
<script src="<?php echo $_layoutParams?>/bootstrap.min.js"></script>-->


<!-- Latest compiled and minified CSS & JS -->
<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="//code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>




<head>
	<meta charset="UTF-8">
	
	<br>
	<title>Inicio de sesión</title>

</head>
<body>


